FROM node:16

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY server/package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy the server source code
COPY server/src ./src
COPY server/config ./config

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["node", "src/app.js"]