version: '3.8'

services:
  server:
    build:
      context: ./docker
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@db:5432/barcode_pos
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db

  client:
    build:
      context: ./docker
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: barcode_pos
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: