openapi: 3.0.0
info:
  title: Barcode POS & Inventory Management API
  description: API documentation for the Barcode POS & Inventory Management SaaS Platform
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
        '401':
          description: Invalid credentials

  /auth/register:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request

  /auth/me:
    get:
      summary: Get current user information
      responses:
        '200':
          description: User information retrieved successfully
        '401':
          description: Unauthorized

  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: List of products
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                barcode:
                  type: string
                categoryId:
                  type: integer
                price:
                  type: number
                stock:
                  type: integer
      responses:
        '201':
          description: Product created successfully

  /products/{id}:
    put:
      summary: Update a product
      parameters:
        - name: id
          in: path
          required: true
          description: Product ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                barcode:
                  type: string
                categoryId:
                  type: integer
                price:
                  type: number
                stock:
                  type: integer
      responses:
        '200':
          description: Product updated successfully
    delete:
      summary: Delete a product
      parameters:
        - name: id
          in: path
          required: true
          description: Product ID
          schema:
            type: integer
      responses:
        '204':
          description: Product deleted successfully

  /inventory:
    get:
      summary: Get inventory status
      responses:
        '200':
          description: Inventory status retrieved successfully
    post:
      summary: Update inventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
                quantity:
                  type: integer
      responses:
        '200':
          description: Inventory updated successfully

  /sales:
    post:
      summary: Create a new sale
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: integer
                      quantity:
                        type: integer
                total:
                  type: number
      responses:
        '201':
          description: Sale created successfully

  /sales/reports:
    get:
      summary: Get sales reports
      responses:
        '200':
          description: Sales reports retrieved successfully

  /customers:
    get:
      summary: Get all customers
      responses:
        '200':
          description: List of customers
    post:
      summary: Create a new customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Customer created successfully

  /tenants/branding:
    get:
      summary: Get tenant branding information
      responses:
        '200':
          description: Tenant branding information retrieved successfully
    put:
      summary: Update tenant branding
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                logo:
                  type: string
                colors:
                  type: object
                  properties:
                    primary:
                      type: string
                    secondary:
                      type: string
      responses:
        '200':
          description: Tenant branding updated successfully